# Generated by Django 5.2 on 2025-06-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_name', models.CharField(max_length=50)),
                ('cource_is', models.IntegerField()),
                ('publish_date', models.IntegerField()),
            ],
        ),
    ]
