# Generated by Django 5.1.6 on 2025-02-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='password',
            new_name='phone',
        ),
    ]
