# Generated by Django 5.2 on 2025-06-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('type_image', models.CharField(choices=[('BR', 'Birthday'), ('SP', 'Sports'), ('STD', 'Student'), ('TC', 'Teacher'), ('DL', 'Diwali'), ('OR', 'Other')], max_length=3)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
