# Generated by Django 5.2 on 2025-06-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credits',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='cource',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='student',
            name='clss',
            field=models.IntegerField(),
        ),
    ]
